### ISSUE TITLE
Can't get the result of the professional----> bad AP

### ISSUE THREAD

**Issue by Lydiagugugaga** [yeonsikch/Unbiased-Teacher#2]
Hello! Thanks for your work.

Since I only have access to 1 GPU, I am using smaller batch size (label: 6images, unlabel: 6 images).

Finally, I get worse Box AP results. AP=8 (for coco standard, 1%sup, base_LR=0.01)
The Loss_box_reg and the Loss_box_reg_pseudo could not be declined, and the total loss is about 0.4 to 0.5 all the time.

How can I reproduce the result of Unbaised-Teacher?

I'm looking forward to your reply!

**Comment by yeonsikch** [comment]
Hi.

Did you learn until end of end?
And Batch size is important because of batch normalization.

I think that you have to ask this paper's author.
I'm not author and I don't exactly know this issue. sorry.

this is author's github.
https://github.com/facebookresearch/unbiased-teacher

Thank you.

**Comment by Lydiagugugaga** [comment]
Thanks very much for your reply. 

I have asked the author about the previous problem before,  but  there was still no clear answer, maybe modifying the unsup_loss_weight and so on, it didin't work in the end. It is estimated that the batchsize has a great influence, so now I choose the smaller dataset to reduce the occupation of GPU memory.

**Can I ask you a new question?**
Because of the limitation of GPU memory, I tried to use the Pascal VOC (smaller than COCO) as my dataset. My device is like yours, I use one GPU for training (3090, Batchsize: label 8, unlabel 8). But the training time is to long, I need to spend 2 days to complete this project. Here is my config( **the same as the author's config**, I am not sure which parameter I can modify to improve the speed):

> ROI_HEADS:
>     NAME: "StandardROIHeadsPseudoLab"
>     LOSS: "FocalLoss"
>     NUM_CLASSES: 20
> INPUT:
>   MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
>   MIN_SIZE_TEST: 600
> SOLVER:
>   LR_SCHEDULER_NAME: "WarmupMultiStepLR"
>   STEPS: (179990, 179995)
>   MAX_ITER: 180000
>   IMG_PER_BATCH_LABEL: 16
>   IMG_PER_BATCH_UNLABEL: 16
>   BASE_LR: 0.01
> DATALOADER:
>   SUP_PERCENT: 100.0
> DATASETS:
>   CROSS_DATASET: True
>   TRAIN: ("voc_2012_trainval",)
>   TRAIN_LABEL: ("voc_2007_trainval",)
>   TRAIN_UNLABEL: ("voc_2012_trainval",)
>   TEST: ("voc_2007_test",)
> SEMISUPNET:
>   Trainer: "ubteacher"
>   BBOX_THRESHOLD: 0.7
>   TEACHER_UPDATE_ITER: 1
>   BURN_UP_STEP: 30000
>   EMA_KEEP_RATE: 0.999
>   UNSUP_LOSS_WEIGHT: 2.0
> TEST:
>   EVAL_PERIOD: 3000
>   EVALUATOR: "COCOeval"

I want to ask you about improving the training speed for advice, because I see that you also use one 3090 for experimentation.

I don’t have much experience in deep learning model training, I hope I can get your guidance.

**Comment by yeonsikch** [comment]
Hi.

This is my conf file for  10% labeled SS-OD.
But your config file have a `SUP_PERCENT: 100.0` 
This mean is you learn Supervised Learning via all labeled data.
This is not Semi-Supervised Learning.
And your `IMG_PER_BATCH_LABEL:16` and `IMG_PER_BATCH_UNLABEL:16` mean your batchsize is `label:unlabel = 16:16`
If this run, fix this size.

And I can recommend you about improving the training speed.
but this may so difficult.

you can NVIDIA/APEX-amp (https://github.com/NVIDIA/apex)
or pytorch-amp (https://pytorch.org/docs/stable/amp.html)

if you wanna this code, you have to modify some code.
So, this is so difficult.

Good Luck.

```
_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  META_ARCHITECTURE: "TwoStagePseudoLabGeneralizedRCNN"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  PROPOSAL_GENERATOR:
    NAME: "PseudoLabRPN"
  RPN:
    POSITIVE_FRACTION: 0.25
    LOSS: "CrossEntropy"
  ROI_HEADS:
    NAME: "StandardROIHeadsPseudoLab"
    LOSS: "FocalLoss"
    NUM_CLASSES: 15
SOLVER:
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  STEPS: (179990, 179995)
  MAX_ITER: 180000
  IMG_PER_BATCH_LABEL: 4
  IMG_PER_BATCH_UNLABEL: 4
  BASE_LR: 0.01
DATALOADER:
  SUP_PERCENT: 10.0
  RANDOM_DATA_SEED: 1
DATASETS:
  CROSS_DATASET: False
  TRAIN: ("vtt_train",)
  TEST: ("vtt_val",)
  TRAIN_LABEL: ("vtt_train",)
  TRAIN_UNLABEL: ("vtt_train",)
SEMISUPNET:
  Trainer: "ubteacher"
  BBOX_THRESHOLD: 0.7
  TEACHER_UPDATE_ITER: 1
  BURN_UP_STEP: 2000
  EMA_KEEP_RATE: 0.9996
  UNSUP_LOSS_WEIGHT: 2.0
TEST:
  EVAL_PERIOD: 1000
  EVALUATOR: "COCOeval"
```
